import type { Metadata } from "next";
import "./globals.css";
import Layout from "../components/layout";
import { ShoppingCardContextProvider } from "../context/shoppingCardContext";

export const metadata: Metadata = {
  title: {
    default: "learn NEXT",
    template: "%s  |  NEXT",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ShoppingCardContextProvider>
          <Layout>{children}</Layout>
        </ShoppingCardContextProvider>
      </body>
    </html>
  );
}
